format = """$username@$hostname $os$fill $time $all$character"""

[username]
show_always = true
format = '\[[$user]($style)'
style_user = 'bold blue'

[hostname]
ssh_only = false
format = '[$hostname]($style)\]'
style = 'bold purple'

[os]
disabled = false
format = '[$symbol]($style)'
style = 'dimmed purple'

[os.symbols]
Arch = "󰣇 "
EndeavourOS = " "

[fill]
symbol = " "

[time]
disabled = false
format = '[$time]($style)'
style = 'dimmed red'

[character]
# Lambda: 󰘧
success_symbol = '[󰘧](bold blue)'
error_symbol = '[󰘧](bold dimmed purple)'
