import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 90, lines = 30 }
# decorations = "none"
opacity = 0.75
dynamic_title = false

[font]
normal.family = "VictorMono NFM"
size = 14
